<?php

namespace App\IssueBundle\Entity\Repository;

/**
 * IssueRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getIssuesCountGruppedByStatus()
    {
        $qb = $this->createQueryBuilder('i');
        $qb->addSelect('w.id')
            ->addSelect('count(i.id)')
            ->join('i.workflow', 'w')
            ->groupBy('w.id');
        $query = $qb->getQuery();

        return $query->getArrayResult();
    }
}
