<?php

namespace App\IssueBundle\Entity;

/**
 * PriorityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
