oro_entity_config:
    issue:
        entity:
            enabled: # boolean
                options:
                    require_schema_update: true
                    priority:           260
                    default_value:      false