items:
    user_items:
        template: IssueBundle:User:userGrid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

    user_crate_task_button:
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        template: IssueBundle:User:createIssueForUser.html.twig
    oro_send_email_button:
            template: IssueBundle:Issue:placeholders/button.html.twig
            acl: oro_email_email_create
    oro_send_email_link:
        template: IssueBundle:Issue:placeholders/link.html.twig
        acl: oro_email_email_create
placeholders:

    view_content_data_additional_information:
        items:
            user_items:
                order: 200
    view_pageActions_after:
        items:
              user_crate_task_button:
                  order: 200