App\IssueBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        description:
            - NotBlank: ~
        priority:
            - NotBlank: ~
        reporter:
            - NotBlank: ~
