App\IssueBundle\Entity\Issue:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: code
    properties:
        summary:
            - NotBlank: ~
            - Length:
                max: 255
        description:
            - NotBlank: ~
        priority:
            - NotBlank: ~
        reporter:
            - NotBlank: ~
