workflows:
    app_issue_workflow:
        label:      'Issue Workflow'
        entity:     App\IssueBundle\Entity\Issue
        start_step: open            # new lead will be created with this step
        steps_display_ordered: true # all steps will be visible in steps widget
        entity_attribute: lead      # lead will be accessible by $lead in actions and conditions

        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            resolved:
                label: 'Resolved'
                order: 30
                allowed_transitions:
                    - reopen
                    - close
            reopened:
                label: 'Reopened'
                order: 30
                allowed_transitions:
                    - start_progress
            closed:
                label: 'Closed'
                order: 30
                allowed_transitions:
                    - reopen
        attributes: ~

        transitions:
            start_progress:
                label:        'Start progress'
                step_to:      in_progress
                transition_definition: start_progress_definition
            close:
                label:        'Close'
                step_to:      closed
                transition_definition: close_definition
                is_unavailable_hidden: false
                frontend_options:
                    icon: 'icon-ok'
                    class: 'btn-success'
            reopen:
                label:        'Reopen'
                step_to:      reopened
                transition_definition: reopen_definition
                is_unavailable_hidden: false
                frontend_options:
                    icon: 'icon-repeat'
            resolve:
                label:        'Resolve Issue'
                step_to:      resolved
                transition_definition: start_progress_definition
        transition_definitions:
            start_progress_definition: ~
            close_definition: ~
            reopen_definition: ~