workflows:
    app_issue_workflow:
        label:      'Issue Workflow'
        entity:     App\IssueBundle\Entity\Issue
        entity_attribute: status
        start_step: open
        steps_display_ordered: true
        steps:
            open:
                label: 'Open'
                order: 10
                allowed_transitions:
                    - start_progress
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            resolved:
                label: 'Resolved'
                order: 30
                allowed_transitions:
                    - reopen
                    - close
            reopened:
                label: 'Reopened'
                order: 30
                allowed_transitions:
                    - start_progress
            closed:
                label: 'Closed'
                order: 30
                allowed_transitions:
                    - reopen
        attributes: ~

        transitions:
            stop_progress:
                label:  'Stop progress'
                step_to:  open
                transition_definition: stop_progress_definition

            start_progress:
                label:        'Start progress'
                step_to:      in_progress
                transition_definition: start_progress_definition
                frontend_options:
                    icon: 'icon-play'
                    class: 'btn-success'
            close:
                label:        'Close'
                step_to:      closed
                transition_definition: close_definition
                is_unavailable_hidden: false
                frontend_options:
                    icon: 'icon-ok'
                    class: 'btn-success'
            reopen:
                label:        'Reopen'
                step_to:      reopened
                transition_definition: reopen_definition
                is_unavailable_hidden: false
                frontend_options:
                    icon: 'icon-repeat'
            resolve:
                label:        'Resolve Issue'
                step_to:      resolved
                transition_definition: start_progress_definition
        transition_definitions:
            start_progress_definition: ~
#                conditions:
#                      @and:
#                              - @not_blank: [$asignee]
#                              - @not_blank: [$reporter]
#                      post_actions:
#                          - @create_entity:
#                              parameters:
#                                  class: Oro\Bundle\NoteBundle\Entity\Note
#                                  attribute: $notes
#                                  data:
#                                      message: $asignee
            stop_progress_definition: ~
            close_definition: ~
            reopen_definition: ~